# Generated by Django 4.0 on 2022-01-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Room',
            new_name='room',
        ),
    ]
